### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Marusia14/___kinozal-template#1]
1)
Отступы не соответствуют поставленной задаче.
![image](https://user-images.githubusercontent.com/8464662/137618031-a25ab64e-1f6a-4eb4-85dd-38dfa68b1ccf.png)

2)
неправильное создание и некорректный вид элемента
![image](https://user-images.githubusercontent.com/8464662/137618052-6c7553e5-7618-4926-a2db-513a7b3ac585.png)

3)
присуствует горизонтальный скрол
![image](https://user-images.githubusercontent.com/8464662/137618073-ad59cec9-47d4-4896-b94c-449b469f56a9.png)

4)
где копирайт?
можете свой текст использовать, но блок в точности такой должен быть
![image](https://user-images.githubusercontent.com/8464662/137618104-a6a77ece-7747-49bc-90ac-8f9811ebf808.png)

**Comment by Marusia14** [comment]
Repository:
https://github.com/Marusia14/___kinozal-template.git

Page:
https://marusia14.github.io/___kinozal-template/

нд, 17 жовт. 2021 о 11:14 Andrey ***@***.***> пише:

**Comment by Alecto** [comment]
Хорошо, ошибок и замечаний нет.
Работа принята.

нд, 17 жовт. 2021 о 17:32 Мария Лемиш ***@***.***> пише:
